# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#    - name: Set up Node.js
#      uses: actions/setup-node@v3
#      with:
#        node-version: 16.18.1
    - name: Setup pnpm
      uses: pnpm/action-setup@v3 
      with:
        version: 9         
    - name: build fe
      run: cd frontend && npm install
    - name: build fe again 
      run: cd frontend && npm run build 

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Setup
      run: go mod download
    - name: Build go
      run: CGO_ENABLED=0 go build .
    - name: Build Docker image
      run: docker build -t aitong/filebrowser:latest .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
    - name: Push Docker image
      run: docker push aitong/filebrowser:latest  
