name: main

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  # linters
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: make lint-frontend

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - run: make lint-backend

  lint:
    runs-on: ubuntu-latest
    needs: [lint-frontend, lint-backend]
    steps:
      - run: echo "done"

  # tests
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: make test-frontend

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - run: make test-backend

  build-frontend:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install
      - name: Build frontend
        run: |
          cd frontend
          pnpm run build
      - name: Archive frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  build-backend:
    runs-on: ubuntu-latest
    needs: [build-frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Install backend dependencies
        run: |
          go mod download
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
      - name: Build backend binaries with frontend
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p dist
          cp -r frontend/dist public
          for os in $GOOS; do
            for arch in $GOARCH; do
              echo "Building for $os/$arch..."
              GOOS=$os GOARCH=$arch go build -o dist/filebrowser_${os}_${arch}
              tar -czvf dist/filebrowser_${os}_${arch}.tar.gz -C dist filebrowser_${os}_${arch}
            done
          done
          rm -rf public
      - name: Archive backend build
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: dist/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build-backend]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Generate version number
        id: version
        run: echo "version=v$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_OUTPUT
      - name: Create and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
      - uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: backend-dist
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: backend-dist/*.tar.gz
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
